name: yolov4-gpu

dependencies:
  - python==3.9.13
  - pip
  - matplotlib
  - opencv
  - cudnn
  - cudatoolkit==10.1.243
  - pip:
    - tensorflow-gpu==2.10.0
    - opencv-python==4.7.0.72
    - lxml
    - tqdm
    - absl-py
    - easydict
    - pillow
